### ISSUE TITLE
Update runtime to 5.13

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.dhsdevelopments.Climaxima#2]

**Comment by lokedhs** [comment]
The latest `org.kde.Platform` runtime is 5.12, as far as I can tell, so it's not possible to update.

**Comment by LeandroStanger** [comment]
![Captura de tela de 2019-09-20 08-06-27](https://user-images.githubusercontent.com/26097419/65322624-ba081e80-db7d-11e9-8603-4adcdccd15a6.png)

**Comment by lokedhs** [comment]
OK. I see now.

However, no other applications that I have installed requires 5.13. They are all of 5.12. For that reason, I'll hold back on upgrading for now.

Thank you for making me aware of the existence of the updated version.
